### ISSUE TITLE
Casper Member page - https://caspermember.com/ , contain Loper Ipsum text instead of Association specific contents

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#10]
[](https://caspermember.com/)On the Casper Member page - [https://caspermember.com/](https://caspermember.com/) , following sections contain Loper Ipsum text instead of Association specific contents

“About” section

“Tools” Section / “Node Explorer” section

**Comment by opticalresolution** [comment]
@devendran-m this page is available if we want to use it, however I don't have any content. 

My solution would be to exclude this page and put /home in its place as the landing page. We can move the link to the donate page to the top menu as well. 

Mocked up:
![Screen Shot 2022-02-22 at 8 55 38 AM](https://user-images.githubusercontent.com/93783672/155147388-78ec6ce6-f10a-4716-bf4d-4ec84890c9b1.png)

Keep in mind the donations page is non-functioning at this time. Perhaps open a pending issue to make that functional before full launch. We can discuss on the next call.

**Comment by devendran-m** [comment]
Thanks, I am fine with the suggestion, however, I will run it past Piotr/Ralf once.
For donations, yes, I will raise an issue to make it functional for full launch.

**Comment by opticalresolution** [comment]
Added content to the landing page and put it back online
