### ISSUE TITLE
[Bug] Copyright footer contains “CasperLabs.io 2021”

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#15]
In the “Make Donation” page - i.e. https://caspermember.com/donate/ the Copyright footer contains “CasperLabs.io 2021”
Also, on https://caspermember.com/member-viewer/ page

**Comment by opticalresolution** [comment]
@devendran-m what would be the most appropriate language for the footer?

**Comment by devendran-m** [comment]
Hi, if we go by existing footer content and placement, then it would be like below. Note- instead of 2021, it would be 2022.
Link to the Trademark and Policy details should present the user with the content that is currently available on https://casper.network/network/trademark-policy

![image](https://user-images.githubusercontent.com/29494759/155716938-f2037aed-3f7e-473c-a121-05cf1b01fd45.png)

**Comment by ledgerleapllc** [comment]
Fixed with https://github.com/ledgerleapllc/CasperAssociationPortal/commit/09ea3bff59a35588c4d910aa92689f374d9a43b4
