### ISSUE TITLE
[Enhancement : UX ] Text indicating to the user that the process may take some time/few minutes to complete.

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#16]
When the “Extracting address” process is running in the “Get Verified” journey’s “Address Verification” flow, it may be helpful to add a text indicating to the user that the process may take some time/few minutes to complete.  

Also in the “Extracting date of birth” process in “Get Verified” journey’s “ID Verification” flow, it may be helpful to add a text indicating to the user that the process may take some time/few minutes to complete.

**Comment by opticalresolution** [comment]
We are not able to edit inside the shufti iframe. There has been an added message before starting that indicated the process could take a few minutes to complete.
