### ISSUE TITLE
[Bug] Incorrect Member Viewer Footer

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#24]
Incorrect footer on the Member Viewer page - Footer still reads casperlabs.io. It should be Casper Association and year 2022.

**Comment by ledgerleapllc** [comment]
Should also be done to https://caspermember.com/node-explorer/

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/CasperAssociationPortal/commit/409e9c25ab05cf26bfb93259ec7da5e4691d360b
