### ISSUE TITLE
[BUG] Password reset process is taking more time than expected to complete

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#29]
Requested password reset. The process did not complete even after ~ 20 - 25 mins.

Reference screenshot;
![image](https://user-images.githubusercontent.com/29494759/160884152-e892f01c-5a2f-40fc-a8c5-9c581ddab045.png)

**Comment by opticalresolution** [comment]
CAMP-259

**Comment by opticalresolution** [comment]
Send grid was not configured properly. This has been fixed.
