### ISSUE TITLE
Casper Account Info Standard - Member Portal & cspr.live integration

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#30]
The requirement is to adopt Casper Account Info Standard and integrate the between Member Portal & MAKE/cspr.live as specified by the standard.

Details of the requirements are below;

> [In reply to Sam Mihal]
> https://github.com/make-software/casper-account-info-standard - it's the official way to identify accounts on the network, and predominantly used by validators to do so, as created in cooperation with the Casper Association (and the contract is owned by the Association). 
> From the get-go of this portal project as we were discussing architecture for it with Charles, this would be integrated in 2 directions. 
> 1. the portal would use the Standard to identify nodes and pull in the available information (much like CSPR.live does, and CasperHolders, and CasperCommunity, and other tools in the ecosystem). and conversely, 
> 2. it would provide a public endpoint that validators can add to their Casper Account Info Standard metadata that would like to their identity verification on the CA portal, so that clients implementing the metadata (e.g. the sites listed above), can carry over the "verified identity" checkmark etc.

**Comment by ledgerleapllc** [comment]
### casper account info standard

1. Public available hashed kyc doc with Shufti reference number as proof. casper_association_kyc_url
2. Branding logo/avatar, png_256/svg
3. Name/description should show both in validator ranking tooltip, and in profile view. name/description

Lastly, insert some placeholder text when info standard has not been found, include link to github url

**Comment by ledgerleapllc** [comment]
Pushed to staging -

Public available hashed kyc doc with Shufti reference number as proof. casper_association_kyc_url. You can find this new feature on the profile view next to your Shufti verification status.

**Comment by ledgerleapllc** [comment]
Name/description should show both in validator ranking tooltip, and in profile view. name/description

**Comment by ledgerleapllc** [comment]
Avatar is now pulled from account info contract and used if user uploaded avatar file does not exist.
