### ISSUE TITLE
Add Casper Association standard footer/privacy policy etc to the mails template

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#39]
Demo II feedback - Add Casper Association standard footer/privacy policy etc to the mails

**Comment by ledgerleapllc** [comment]
Using same footer from landing page. Compact to fit inside the email footers

**Comment by ledgerleapllc** [comment]
https://github.com/ledgerleapllc/CasperAssociationPortalBackend/pull/13

**Comment by ledgerleapllc** [comment]
![email](https://user-images.githubusercontent.com/69469839/167181130-263b874a-f148-4dcd-a9e2-684386c82ffb.png)
