### ISSUE TITLE
Casper Association Logo is not rendering correctly in Password reset email

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#46]
Casper Association Logo is not rendering correctly in Password reset email received;

Please refer below screenshot for details;
![image](https://user-images.githubusercontent.com/29494759/166201554-8d59145d-13e3-4339-b536-83ccb258a8e2.png)

**Comment by ledgerleapllc** [comment]
It appears that any links embedded into our emails relayed by the Sendgrid utilize the CNAME url2176 to proxy the link off their servers, thus changing the link URL. Every emailing service I've known (Mailchimp, Drip, etc) do this sanitation step as common practice. However we are facing an SSL issue in that department currently, which means the image is being properly filtered out from the email, as it is recognized as "unsafe content." Once we fix the underlying SSL issue for subdomain url2176, then I am confident this issue will be resolved as well.

**Comment by ledgerleapllc** [comment]
Also went ahead and pushed a fix for that footer styling issue. ^

**Comment by ledgerleapllc** [comment]
All fixed:

**Comment by ledgerleapllc** [comment]
All fixed
![email](https://user-images.githubusercontent.com/69469839/167181022-992656ec-124b-4c8a-afcc-eb524ce0078f.png)
