### ISSUE TITLE
Certificate Error when trying to reset password using link from 'Reset Password'  email

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#47]
Facing the below-mentioned certificate error when trying to reset password using link from 'Reset Password'  email;

![image](https://user-images.githubusercontent.com/29494759/166201824-c92b4ff7-0232-4b49-b30e-76d12a44fa9c.png)

**Comment by ledgerleapllc** [comment]
Dev and I resolved this issue by changing the Sendgrid CNAME records earlier today.
