### ISSUE TITLE
[Bug] PDF format of ID document uploaded is not recognised

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#7]
Issue - In “Get Verified” User Journey’s ID Verification flow, PDF format of ID document uploaded is not recognised. Note - Issue - PDF document is uploaded it is not recognised, whilst a jpeg is recognised correctly

Expected - PDF document is one of the options. Therefore PDF should also be recognised correctly and the details of the document displayed in the preview page - i.e. “Can you clearly see the information in the image below?” section.

Supporting screenshots
When uploading PDF format

![PDF_Not_Recog_0](https://user-images.githubusercontent.com/29494759/155077695-939a2d2e-1855-4d2a-be84-5091c66e8d13.png)

![PDF_Not_Recog_1](https://user-images.githubusercontent.com/29494759/155077746-f639ef4f-de26-43b7-a445-25368a81ffb8.png)

**Comment by opticalresolution** [comment]
This i-frame is controlled by shufti. We verified in the shufti documentation that the i-frame will accept JPG, JPEG, PNG, PDF
