### ISSUE TITLE
Beta Testing Feedback - Fix Rate %, update Uptime % and rename "Self Stake"

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#70]
The objective is to fix the issues shared by the Beta Testing team.

> The node explorer shows wrong numbers for different columns:
> https://members-staging.casper.network/node-explorer
> 
> - The Rate -> Instead of 0.01% it should be 1% (details page is right though)
> - Uptime of 1% is most probably wrong?
> - "Self Stake" should probably be renamed to "Total Stake" as it is on cspr.live

**Comment by ledgerleapllc** [comment]
Commit: https://github.com/ledgerleapllc/CasperAssociationPortal/pull/71/commits/0cb49b33ea0c08fac7cbbbaacb9ae43aeeee3d46
Commit: https://github.com/ledgerleapllc/CasperAssociationPortal/pull/71/commits/e5014ed9c15c04dea42478a1acba274a515ecd86

**Comment by ledgerleapllc** [comment]
Commit: https://github.com/ledgerleapllc/CasperAssociationPortal/commit/d499c5fa0d41343ec78198947bee8ccc4db13176

**Comment by ledgerleapllc** [comment]
![updated-labels](https://user-images.githubusercontent.com/69469839/178558179-4a06a331-999a-44c0-a070-11d29c2956de.jpg)
