### ISSUE TITLE
[Bug] Address not extracted from the uploaded utility bill

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#8]
After uploading the supporting document for address verification, the address is not extracted from the document uploaded and displayed on the “Confirm your Address information and make edits if needed” page.

Screenshot;
![Address_Extract](https://user-images.githubusercontent.com/29494759/155078330-6a530d9e-d5b2-4dff-a842-3ab90d87daf8.png)

**Comment by opticalresolution** [comment]
This was also a Shufti i-frame problem. Verified in the documentation that it will extract the appropriate documents
