### ISSUE TITLE
[Bug] “Verified Since” status is reflected as “VERIFIED” on "My Profile" page when verification is pending

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#9]
When the verification is pending, “Verified Since” status is reflected as “VERIFIED” on the “My Profile” page;

![Verify1](https://user-images.githubusercontent.com/29494759/155078730-284c9ea4-354f-46bd-a6ff-86833c93c8fd.png)

![Verify2](https://user-images.githubusercontent.com/29494759/155078755-e6a2579c-d665-4b47-a13d-af9eb770fd9f.png)

**Comment by opticalresolution** [comment]
This issue has been addressed and fixed
