### ISSUE TITLE
`Invalid Date EST` error in `Uptime Warning` message on the `Membership` page

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#90]
Issue - `Invalid Date EST` error in `Uptime Warning` message on the `Membership` page

Expected - A valid date and time in EST should be included in the `Uptime Warning` message

Actual - No valid date and time in EST in the `Uptime Warning` message. Refer below screenshot for details.

![image](https://user-images.githubusercontent.com/29494759/185120555-554db259-2a4a-48c2-84ae-4e816314630f.png)

**Comment by ledgerleapllc** [comment]
Fix incoming: https://github.com/ledgerleapllc/CasperAssociationPortal/pull/95
