### ISSUE TITLE
`Invalid Date EST` error in the 'Block Height Average warning' message on the `Membership` page

### ISSUE THREAD

**Issue by devendran-m** [ledgerleapllc/CasperAssociationPortal#91]
Issue - `Invalid Date EST` error in the 'Block Height Average warning' message on the `Membership` page

Expected - A valid date and time in EST should be included in the 'Block Height Average warning' message

Actual - No valid date and time in EST in the 'Block Height Average warning' message. Refer to below screenshot for details.
![image](https://user-images.githubusercontent.com/29494759/185122057-c808d31e-e175-435a-add7-3a3c4107588f.png)

**Comment by ledgerleapllc** [comment]
Fix incoming https://github.com/ledgerleapllc/CasperAssociationPortal/pull/95
